### ISSUE TITLE
target_dir's parent folders are not created, errors instead

### ISSUE THREAD

**Issue by GeckoEidechse** [MCOfficer/zip-extract#13]
Based on the comment in the [usage example](https://docs.rs/zip-extract/0.1.2/zip_extract/#usage), i.e. this one

```rust
let target_dir = PathBuf::from("my_target_dir"); // Doesn't need to exist
```

I assumed that supplying e.g. `some/path/to/my_target_dir` the library would create the entire path, not just the last folder...

So is creating only the last folder intentional behaviour or a bug? ^^

**Comment by MCOfficer** [comment]
Kind of neither - I think I simply never thought of multiple non-existing folders. 

At the same time, I kind of don't like the prospect of implicitly creating long chains of folders. I think in the future creating *all* folders should be an explicit opt-in, with no folders being created otherwise. And for now I will correct the documentation to reflect the current behavior.

Edit: I am a fool and this is in fact documented properly:
https://github.com/MCOfficer/zip-extract/blob/5e0de20c5f6ddb91e9f38b71aba12695687859a6/src/lib.rs#L59-L61

**Comment by GeckoEidechse** [comment]
Oh whoops, maybe I should've gone past the first page on the docs, my bad ^^"
